version: "3"
services:
  # Custom Application Service
  app:
    build:
      dockerfile: "Dockerfile"  # Uses local Dockerfile
      context: .               # Build context is current directory
    ports:
      - "8080"                # Exposes port 8080
    command: [
      "-address=${CONTRACT_ADDRESS}",
      "-from",
      "-to",
      "Transfer",
      "Approval"
    ]

  # PostgreSQL Database Service
  postgres:
    image: "postgres:15.2"    # Uses official Postgres image
    ports:
      - "5432"               # Exposes default Postgres port
    restart: always          # Automatic restart policy
    environment:            # Database configuration
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - PGDATA=var/lib/postgres/data/pgdata


# docker compose build --no-cache
# docker compose up -d
# docker compose ps
# docker compose logs
# docker compose down
# docker compose 