version: "3"
services:
  # Custom Application Service
  app:
    build:
      dockerfile: "Dockerfile"  # Uses local Dockerfile
      context: .               # Build context is current directory
    networks:
      - app-network
    stdin_open: true        # Allows stdin to be open for interactive commands
    tty: true               # Allocates a pseudo-TTY
    ports:
      - "8080:8080"                # Exposes port 8080
    command: [
      "-address=0xdBFC942264f5CebF8C59f4065af2EFfB92D12475",
      "-from=100000000",
      "-to=100010000",
      "Transfer",
      "Approval"
    ]
    depends_on:
      - postgres

  # PostgreSQL Database Service
  postgres:
    image: "postgres:15.2"    # Uses official Postgres image
    networks:
      - app-network
    ports:
      - "5432:5432"             # Exposes default Postgres port
    restart: always          # Automatic restart policy
    environment:            # Database configuration
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=var/lib/postgres/data/pgdata

networks:
  app-network:
    driver: bridge


# docker compose build --no-cache
# docker compose up -d
# docker compose ps
# docker compose logs
# docker compose down
# docker compose 